### ISSUE TITLE
Hook up manual controls in the "controls" templates

### ISSUE THREAD

**Issue by uncletammy** [2fatdotco/sxSpeech#3]
We need to be able to manually control the lamps from the admin dashboard (controls partial).  I've put in stubbs that covers all the functionality we need.  It just needs SDK methods created and the controller code to handle the events.

Feel free to change or erase the stubbs.  You don't have to build on them if it's easier for you to start from scratch.

All buttons and sliders need to send a POST to `/lamps/command` with their corresponding object.  Examples of each are included below.
- Level : `{"level":11}`
- Pulse : `{"pulse":3000}`
- Fadeup : `{"fadeup":2250}`
- SetFreakLevel : `{"setFreakLevel":16}`
- Freakout: `{"freakout":3000}`
- setRed : `{"setRed":true}`
  `setWhite : {"setWhite":true}`

All calls should fire only when the user selects a setting within the range (or clicks the button).  The ng-change directive fires many change events.  We need only one API call to be fired per setting changed.

**Comment by lukeheath** [comment]
Thanks for getting this started. I moved it all over to the 'Dashboard" screen so it's consolidated.

For out about a cool angular options: `ng-model-options`, which lets us set a debounce directly on the model. I have it set to 1000ms for each input, but you can change that if you want for each one. It's working well, only fires after a 1 second delay with the final value.

I'll check in again tonight and do a little more work. Let me know if you spot anything that needs to be addressed.
